package it.polimi.se2018.classes.effects;

public enum EffectType {
    ROTATEDICEMODIFY,
    UPORDOWNVALUEMODIFY,
    NEWRANDOMVALUEMODIFY,
    DRAFTPOOLROUNDTRACKEXCHANGE,
    DRAFTPOOLBAGEXCHANGE
}
