package it.polimi.se2018.classes.model.effects;

public enum EffectType {
    ROTATEDICEMODIFY,
    UPORDOWNVALUEMODIFY,
    NEWRANDOMVALUEMODIFY,
    DRAFTPOOLROUNDTRACKEXCHANGE,
    DRAFTPOOLBAGEXCHANGE,
    NOVALUEBOUND,
    NOCOLORBOUND
}
